### ISSUE TITLE
Remove operation is not working #1

### ISSUE THREAD

**Issue by PritoM-Debnath** [PritoM-Debnath/PerkyRabbit#1]
# From view i want to pass a model. 

by this line i want a model to pass to the controller,
` <a asp-controller="Category" asp-action="RemoveCategory" asp-route-_category="@item" class="text-warning btn btn-dark">Delete</a> `

From the controller i used this code, 
`public async Task<IActionResult> RemoveCategory(ExpenseCategory _category)
    { 
        if (ModelState.IsValid)
        {
            await categoryRepo.RemoveExpenseCategory(_category);
        }
        return RedirectToAction("Index");
    }`
    
I want to fix this code.

**Comment by tamimprime** [comment]
In your scenario, you're trying to pass a ExpenseCategory model from a view to a controller action when clicking on a link. However, when you click a link, it typically performs a GET request, which doesn't include a request body to send complex objects like models. Instead, you can pass data via query parameters or use a form with a POST request to send the data.

**Comment by PritoM-Debnath** [comment]
Yes, in my opinion. I ought to use the ID.
